FROM jupyter/datascience-notebook

RUN pip install jupyterlab
RUN pip install mglearn
RUN pip install graphviz
RUN pip install nltk
RUN pip install wordcloud
RUN pip install janome
RUN pip install feather-format
RUN pip install fastai==0.7.0
RUN pip install torchtext==0.2.3
RUN jupyter serverextension enable --py jupyterlab
