FROM jupyter/datascience-notebook

RUN pip install jupyterlab
RUN pip install mglearn
RUN pip install graphviz
RUN pip install nltk
RUN pip install wordcloud
RUN jupyter serverextension enable --py jupyterlab
